version: '3'

services:
  node1:
    container_name: 'control-host'
    image: ubuntu:23.04
    command: /bin/bash 
    tty: true
    volumes:
      - ./scripts/bootstrap-control.sh:/usr/local/bin/bootstrap-control.sh
    networks:
      my_network:
        ipv4_address: 172.18.0.2

  node2:
    container_name: 'server-1'
    image: ubuntu:23.04
    command: bootstrap-script-inject.sh bootstrap-server.sh
    tty: true
    volumes:
      - ./scripts/bootstrap-bashrc-content.txt:/root/.bootstrap-bashrc-content.txt
      - ./scripts/bootstrap-server.sh:/usr/local/bin/bootstrap-server.sh
      - ./scripts/bootstrap-script-inject.sh:/usr/local/bin/bootstrap-script-inject.sh
    networks:
      my_network:
        ipv4_address: 172.18.0.3

  node3:
    container_name: 'server-2'
    image: ubuntu:22.04
    command: /bin/bash
    tty: true
    volumes:
      - ./scripts/bootstrap-server.sh:/usr/local/bin/bootstrap-server.sh
    networks:
      my_network:
        ipv4_address: 172.18.0.4

  node4:
    container_name: 'server-3'
    image: oraclelinux:8
    command: /bin/bash
    tty: true
    volumes:
      - ./scripts/bootstrap-server.sh:/usr/local/bin/bootstrap-server.sh
    networks:
      my_network:
        ipv4_address: 172.18.0.5

  node5:
    container_name: 'server-4'
    image: oraclelinux:8
    command: /bin/bash
    tty: true
    volumes:
      - ./scripts/bootstrap-server.sh:/usr/local/bin/bootstrap-server.sh
    networks:
      my_network:
        ipv4_address: 172.18.0.6


networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
