version: '3'

services:
  node1:
    container_name: 'control-host'
    image: ubuntu:23.04
    command: /bin/bash 
    tty: true
    volumes:
      - ./scripts/bootstrap-control.sh:/root/scripts/bootstrap-control.sh

  node2:
    container_name: 'server-1'
    image: ubuntu:23.04
    command: /bin/bash
    tty: true
    volumes:
      - ./scripts/bootstrap-server.sh:/root/scripts/bootstrap-server.sh

  node3:
    container_name: 'server-2'
    image: ubuntu:22.04
    command: /bin/bash
    tty: true
    volumes:
      - ./scripts/bootstrap-server.sh:/root/scripts/bootstrap-server.sh

  node4:
    container_name: 'server-3'
    image: oraclelinux:8
    command: /bin/bash
    tty: true
    volumes:
      - ./scripts/bootstrap-server.sh:/root/scripts/bootstrap-server.sh

  node5:
    container_name: 'server-4'
    image: oraclelinux:8
    command: /bin/bash
    tty: true
    volumes:
      - ./scripts/bootstrap-server.sh:/root/scripts/bootstrap-server.sh
